POST http://localhost:3030/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "identifier": "student",
  "password": "student"
}

###
POST http://localhost:3030/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "data": {
    "identifier": "student",
    "password": "studentbcai",
    "role": "STUDENT"
  }
}

###
POST http://localhost:3030/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "data": {
    "identifier": "teacher",
    "password": "teacherbcai",
    "role": "TEACHER"
  }
}

###
POST http://localhost:3030/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "data": {
    "name": "New User",
    "username": "newuser",
    "email": "newuser@bacacerdas.ai",
    "password": "newuser",
    "confirmPassword": "newuser",
    "role": "STUDENT",
    "acceptTerms": true
  }
}